initial rewrite

diff --git a/tinyramfs b/tinyramfs
--- a/tinyramfs
+++ b/tinyramfs
@@ -3,145 +3,220 @@
 # https://shellcheck.net/wiki/SC2154
 # shellcheck disable=2154
 
+set -e
+
 # TODO add version
-usage()
-{
-    cat >&2 << EOF
-usage: ${0##*/} [option]... <output>
-    -c <file>  set path to config
+usage() {
+    cat <<EOF >&2
+usage: $(basename "$0") [option]... <output>
     -k <kern>  set kernel version
     -m <path>  set path to modules
-    -l         enable local mode
+    -H <hooks> set hooks (comma-separated)
+    -c <util>  set compression utility
+    -n         don't copy kernel modules (for a non-modular kernel)
+    -M         detect modules to copy
     -d         enable debug mode
-    -f         overwrite initramfs image
     -h         display this message
 EOF
 
     exit "$1"
 }
 
-init_base()
-{
-    print 'creating ramfs structure'
+print() {
+    printf '%s %s\n' "${2:->>}" "$1"
+}
+
+die() {
+    print "${1:-unexpected error occurred}" "!>" >&2
+    exit 1
+}
+
+add_config() {
+    printf '%s=%s\n' "$1" "$2" >>"$tmpdir/etc/tinyramfs.conf"
+}
+
+init_base() {
+    print "creating ramfs structure"
 
     mkdir -p "${tmpdir:=${TMPDIR:-/tmp}/tinyramfs.$$}"
 
-    # https://shellcheck.net/wiki/SC2015
-    # shellcheck disable=2015
-    [ "$debug" ] && set -x || trap 'rm -rf "$tmpdir"' EXIT INT
-
-    (
-        cd "$tmpdir"
-
-        # https://wikipedia.org/wiki/Filesystem_Hierarchy_Standard
-        mkdir -p \
-            dev sys tmp run var proc root \
-            usr/lib usr/bin mnt/root etc/tinyramfs
-
-        ln -s lib usr/lib64
-        ln -s usr/lib lib64
-        ln -s usr/lib lib
-        ln -s usr/bin bin
-        ln -s usr/bin sbin
-        ln -s ../run  var/run
-        ln -s ../run/lock var/lock
-        ln -s bin     usr/sbin
-
-        ln -s lib/tinyramfs/init.sh init
-        ln -s ../lib/tinyramfs/helper.sh bin/helper
-    )
-
-    for _bin in \
-        \[ sh ln env mkdir sleep \
-        printf switch_root mount
-    do
-        copy_exec "$_bin"
-    done
-
-    if ! command -v ldd > /dev/null; then
-        print 'unable to find ldd' '~>'
-    fi
-
-    if ! command -v blkid > /dev/null; then
-        print 'unable to find blkid' '~>'
+    if [ -n "$debug" ]; then
+        set -x
     else
-        copy_exec blkid
+        trap 'rm -rf "$tmpdir"' EXIT INT
     fi
 
-    copy_file "$config" /etc/tinyramfs/config    0644
-    copy_file "$init"   /lib/tinyramfs/init.sh   0755
-    copy_file "$devh"   /lib/tinyramfs/helper.sh 0755
-    copy_file "$shrd"   /lib/tinyramfs/common.sh 0755
+    for dir in dev sys proc lib bin etc mnt; do
+        mkdir -p "$tmpdir/$dir"
+    done
+    ln -s . "$tmpdir/usr"
+    ln -s bin "$tmpdir/sbin"
+    ln -s lib "$tmpdir/lib64"
+
+    copy_exec busybox
+    for bin in $("$tmpdir/bin/busybox" --list); do case "$bin" in
+        busybox) continue;;
+        *) ln -s busybox "$tmpdir/bin/$bin";;
+    esac; done
+
+    [ -n "$root" ] && add_config root "$root"
+    [ -n "$rootfstype" ] && add_config rootfstype "$rootfstype"
+    [ -n "$rootflags" ] && add_config rootflags "$rootflags"
+    [ -n "$ro" ] && add_config ro true
+    [ -n "$rw" ] && add_config rw true
+    [ -n "$init" ] && add_config init "$init"
+
+    copy_file /usr/lib/tinyramfs/init.sh /init 755
 }
 
-copy_hooks()
-{
+copy_file() {
+    file="$1"
+    dest="$2"
+    mode="${3:-644}"
+    strip="$4"
+
+    install -D -m "$mode" "$file" "$tmpdir/$dest"
+
+    if [ -n "$strip" ]; then
+        strip "$tmpdir/$dest" >/dev/null 2>&1 || :
+    fi
+}
+
+copy_exec() {
+    bin="$(command -v "$1")"
+
+    case "$bin" in
+        /*) ;;
+        "") die "unable to find command: $1";;
+        *)
+            # https://shellcheck.net/wiki/SC2086
+            # shellcheck disable=2086
+            { IFS=:; set -- $PATH; unset IFS; }
+
+            for dir; do
+                _bin="$dir/$bin"
+                if [ -x "$_bin" ]; then
+                    bin="$_bin"
+                    break
+                fi
+            done
+
+            if ! [ -x "$bin" ]; then
+                die "unable to find command: $bin"
+            fi
+            ;;
+    esac
+
+    copy_file "$bin" "/bin/$(basename "$bin")" 755 strip
+
+    ldd "$bin" 2>/dev/null |
+        while IFS= read -r lib; do
+            lib="/${lib#*/}"
+            lib="${lib% *}"
+
+            if [ -e "$lib" ]; then
+                copy_file "$lib" "/lib/$(basename "$lib")" 755 strip
+            fi
+        done
+}
+
+copy_kmod() {
+    modprobe -S "$kernel" -D "$1" 2>/dev/null |
+        while read -r _ mod _; do
+            case "$mod" in
+              /*) copy_file "$mod" "$mod"
+            esac
+        done
+}
+
+# TODO allow full path to hook
+copy_hooks() {
     # https://shellcheck.net/wiki/SC2086
     # shellcheck disable=2086
+    add_config hooks "$hooks"
     { IFS=,; set -- $hooks; unset IFS; }
 
-    for _hook; do
-        copy_hook "$_hook"
+    for hook; do
+        path="/usr/lib/tinyramfs/hook/$hook"
+        if ! [ -f "$path/install" ] \
+                && ! [ -f "$path/init" ] \
+                && ! [ -f "$path/init.late" ]; then
+            die "unable to find hook: $hook"
+        fi
+
+        for ext in init init.late; do
+            if ! [ -f "$path/$ext" ]; then
+                continue
+            fi
+
+            print "copying hook: $hook/$ext"
+
+            copy_file "$path/$ext" "/lib/hook/$hook/$ext"
+        done
+
+        print "evaluating hook: $hook"
+
+        # https://shellcheck.net/wiki/SC1090
+        # shellcheck disable=1090
+        if [ -f "$path/install" ]; then
+            . "$path/install"
+        fi
     done
 }
 
-copy_modules()
-{
+copy_modules() {
     # Skip this function if kernel
     # compiled with builtin modules.
-    if [ "$monolith" ]; then
+    if [ -n "$monolith" ]; then
         return
-
-    elif [ "$hostonly" ]; then
-        print 'copying hostonly modules'
+    elif [ -n "$hostonly" ]; then
+        print "copying hostonly modules"
 
         # Perform autodetection of modules via /sys
         # https://wiki.archlinux.org/index.php/Modalias
         find /sys/devices -name modalias -exec sort -u {} + |
+            while IFS= read -r mod; do
+                # Skip unneeded modules and skip modules which
+                # depends on them as well.
+                case "$(modprobe -S "$kernel" -D "$mod")" in
+                    *wmi*|*gpu*|*net*) continue;;
+                esac 2>/dev/null
 
-        while read -r _mod; do
-            # Skip unneeded modules and skip modules which
-            # depends on them as well.
-            case $(modprobe -S "$kernel" -D "$_mod") in
-                *wmi* | *gpu* | *net*) continue ;;
-            esac 2> /dev/null
+                copy_kmod "$mod"
+            done
 
-            copy_kmod "$_mod"
-        done
-
-        if [ "$root_type" ]; then
+        if [ -n "$root_type" ]; then
             copy_kmod "$root_type"
         else
-            while read -r _ _dir _type _; do
-                [ "$_dir" = / ] && break
-            done < /proc/mounts || panic 'unable to detect rootfs module'
+            while read -r _ dir type _; do
+                if [ "$dir" = / ]; then
+                    break
+                fi
+            done </proc/mounts || die "unable to detect rootfs module"
 
-            copy_kmod "$_type"
+            copy_kmod "$type"
         fi
     else
-        print 'copying all modules'
+        print "copying all modules"
 
         (
-            cd "${moddir}/${kernel}/kernel"
+            cd "$moddir/$kernel/kernel"
 
             find \
                 fs lib arch crypto drivers/md drivers/ata drivers/scsi \
                 drivers/block drivers/virtio drivers/usb/host \
-                drivers/usb/storage drivers/input/keyboard -type f 2> /dev/null |
-
-            while read -r _mod; do
-                copy_file "$_mod" "/lib/modules/${kernel}/kernel/${_mod}" 0644
-            done
+                drivers/usb/storage drivers/input/keyboard -type f 2>/dev/null |
+                while IFS= read -r mod; do
+                    copy_file "$mod" "/lib/modules/$kernel/kernel/$mod"
+                done
         )
     fi
 
-    copy_exec modprobe
+    copy_file "$moddir/$kernel/modules.order" \
+              "/lib/modules/$kernel/modules.order"
 
-    copy_file "${moddir}/${kernel}/modules.order" \
-              "/lib/modules/${kernel}/modules.order" 0644
-
-    copy_file "${moddir}/${kernel}/modules.builtin" \
-              "/lib/modules/${kernel}/modules.builtin" 0644
+    copy_file "$moddir/$kernel/modules.builtin" \
+              "/lib/modules/$kernel/modules.builtin"
 
     copy_file "${moddir}/${kernel}/modules.builtin.modinfo" \
               "/lib/modules/${kernel}/modules.builtin.modinfo" 0644
@@ -149,59 +224,37 @@ copy_modules()
     depmod -b "$tmpdir" "$kernel"
 }
 
-create_image()
-{
-    print 'generating initramfs image'
+create_image() {
+    print "generating initramfs image"
 
-    [ -z "$force" ] && [ -e "$output" ] &&
-        panic 'initramfs image already exist'
+    (cd "$tmpdir" && find . | cpio -oH newc -R +0:+0 2>/dev/null) | ${compress:-cat} >"$output" ||
+        die "failed to generate initramfs image"
 
-    (cd "$tmpdir" && find . | cpio -oH newc 2> /dev/null) | ${compress:-cat} > "$output" ||
-        panic 'failed to generate initramfs image'
-
-    print "done: $output" '+>'
+    print "done: $output" "+>"
 }
 
-while getopts c:k:m:ldfh opt; do case $opt in
-    c) config=$OPTARG ;;
-    k) kernel=$OPTARG ;;
-    m) moddir=$OPTARG ;;
-    l) local=1 ;;
-    d) debug=1 ;;
-    f) force=1 ;;
-    h) usage 0 ;;
-    ?) usage 2 ;;
+while getopts k:m:H:c:nMdh opt; do case "$opt" in
+    k) kernel="$OPTARG";;
+    m) moddir="$OPTARG";;
+    H) hooks="$OPTARG";;
+    c) compress="$OPTARG";;
+    n) monolithic="true";;
+    M) hostonly="true";;
+    d) debug="true";;
+    h) usage 0;;
+    ?) usage 2;;
 esac; done
 
 shift "$((OPTIND - 1))"
 
-# https://shellcheck.net/wiki/SC2015
-# shellcheck disable=2015
-[ "$1" ] && output=$1 || usage 2
-
-[ "$local" ] && {
-    init="${PWD}/lib/init.sh"
-    shrd="${PWD}/lib/common.sh"
-    devh="${PWD}/lib/helper.sh"
-}
+if [ -n "$1" ]; then
+    output="$1"
+else
+    usage 2
+fi
 
 : "${kernel:=$(uname -r)}"
 : "${moddir:=/lib/modules}"
-: "${init:=/lib/tinyramfs/init.sh}"
-: "${devh:=/lib/tinyramfs/helper.sh}"
-: "${shrd:=/lib/tinyramfs/common.sh}"
-
-# -e: Exit if command return status greater than 0
-# -f: Disable globbing *?[]
-set -ef
-
-# https://shellcheck.net/wiki/SC1090
-# shellcheck disable=1090
-. "$shrd"
-
-# https://shellcheck.net/wiki/SC1090
-# shellcheck disable=1090
-. "${config:=/etc/tinyramfs/config}"
 
 init_base
 copy_hooks
